### DISCUSSION TITLE
Personal access token does not seem to work

### DISCUSSION THREAD

**Discussion by dawidvanzyl** [NasAmin/trx-parser#186] [Q&A]
I have configured trx-parser in my workflow as follows:
```
    - name: Parse Trx files
      uses: NasAmin/trx-parser@v0.1.1
      with:
        TRX_PATH: ${{ github.workspace }}/TestResults
        REPO_TOKEN: ${{ secrets.TRX_PARSER_TOKEN }}
        IGNORE_FAILURE: 'true'
```

I keep getting a result stating that I need to authenticate via a GitHub App.
```
Run NasAmin/trx-parser@v0.1.1
  with:
    TRX_PATH: /home/runner/work/PanoramaMusic.Identity/PanoramaMusic.Identity/TestResults
    REPO_TOKEN: ***
    IGNORE_FAILURE: true
  env:
    DOTNET_ROOT: /home/runner/.dotnet
Finding Trx files in: /home/runner/work/PanoramaMusic.Identity/PanoramaMusic.Identity/TestResults
Files count: 1
Processing 1 trx files
Transforming file /home/runner/work/PanoramaMusic.Identity/PanoramaMusic.Identity/TestResults/_fv-az133-472_2021-07-31_21_53_47.trx
Checking for failing tests
Creating PR check for PANORAMAMUSIC IDENTITY.TESTS
Creating status check for GitSha: 736dfed83f5a46d2370fbec81581f815de80d292 on a pull request event
Check time is: Sat, 31 Jul 2021 21:53:48 GMT
Error: You must authenticate via a GitHub App.
```

The personal token setup provide _repo_ and _workflow_ scopes.
As an additional note, I am using two factor authentication.

Any suggestions why I'm getting an authentication error?
