### ISSUE TITLE
Dependabot and GH API access

### ISSUE THREAD

**Issue by jnus** [NasAmin/trx-parser#248]
Been running into some issues with this action and Dependabot PR's, when uploading the test result to the GH API. I've got a organization level token specified ,(ORG_GITHUB_TOKEN) as the REPO_TOKEN parameter, since Dependabot does not have access to GITHUB-TOKEN but get the following errror 

Syntax
```
    - name: Parse Trx files
      uses: NasAmin/trx-parser@v0.2.0
      id: trx-parser
      if: always()
      with:
        TRX_PATH: ${{ github.workspace }}/TestResults
        REPO_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
```

Error
```
....
Creating PR check for ORBIT UNITTESTS
Creating status check for GitSha: c040653ee8bead3071fee97ac7d27f52[18](https://github.com/segesdk/kvg-orbit-api/runs/5380650173?check_suite_focus=true#step:7:18)6c681d on a pull request event
Check time is: Tue, 01 Mar 2022 [19](https://github.com/segesdk/kvg-orbit-api/runs/5380650173?check_suite_focus=true#step:7:19):09:12 GMT
Error: Resource not accessible by integration
....
```

Should Dependabot not be able to write to GH API with this?
